#!/bin/bash

# Environment Configuration Generator for QuikApp
# This script generates lib/config/env_config.dart from Codemagic environment variables

set -e

echo "🔧 Generating environment configuration..."

# Create the config directory if it doesn't exist
mkdir -p lib/config

# Generate the env_config.dart file
cat > lib/config/env_config.dart << 'EOF'
// This file is auto-generated by lib/scripts/utils/gen_env_config.sh
// Do not edit manually - it will be overwritten during build

class EnvConfig {
  // App Metadata & Versioning
  static const String appId = String.fromEnvironment('APP_ID', defaultValue: '1002');
  static const String workflowId = String.fromEnvironment('WORKFLOW_ID', defaultValue: 'ios-workflow');
  static const String branch = String.fromEnvironment('BRANCH', defaultValue: 'main3');
  static const String userName = String.fromEnvironment('USER_NAME', defaultValue: 'prasannasrie');
  static const String versionName = String.fromEnvironment('VERSION_NAME', defaultValue: '1.0.6');
  static const String versionCode = String.fromEnvironment('VERSION_CODE', defaultValue: '68');
  static const String appName = String.fromEnvironment('APP_NAME', defaultValue: 'Twinklub App');
  static const String orgName = String.fromEnvironment('ORG_NAME', defaultValue: 'JPR Garments');
  static const String webUrl = String.fromEnvironment('WEB_URL', defaultValue: 'https://twinklub.com/');
  static const String emailId = String.fromEnvironment('EMAIL_ID', defaultValue: 'prasannasrinivasan32@gmail.com');

  // Package Identifiers
  static const String pkgName = String.fromEnvironment('PKG_NAME', defaultValue: 'com.twinklub.twinklub');
  static const String bundleId = String.fromEnvironment('BUNDLE_ID', defaultValue: 'com.twinklub.twinklub');

  // Feature Flags
  static const bool pushNotify = bool.fromEnvironment('PUSH_NOTIFY', defaultValue: true);
  static const bool isChatbot = bool.fromEnvironment('IS_CHATBOT', defaultValue: true);
  static const bool isDomainUrl = bool.fromEnvironment('IS_DOMAIN_URL', defaultValue: true);
  static const bool isSplash = bool.fromEnvironment('IS_SPLASH', defaultValue: true);
  static const bool isPulldown = bool.fromEnvironment('IS_PULLDOWN', defaultValue: true);
  static const bool isBottommenu = bool.fromEnvironment('IS_BOTTOMMENU', defaultValue: true);
  static const bool isLoadInd = bool.fromEnvironment('IS_LOAD_IND', defaultValue: true);

  // Permissions
  static const bool isCamera = bool.fromEnvironment('IS_CAMERA', defaultValue: false);
  static const bool isLocation = bool.fromEnvironment('IS_LOCATION', defaultValue: false);
  static const bool isMic = bool.fromEnvironment('IS_MIC', defaultValue: true);
  static const bool isNotification = bool.fromEnvironment('IS_NOTIFICATION', defaultValue: true);
  static const bool isContact = bool.fromEnvironment('IS_CONTACT', defaultValue: false);
  static const bool isBiometric = bool.fromEnvironment('IS_BIOMETRIC', defaultValue: false);
  static const bool isCalendar = bool.fromEnvironment('IS_CALENDAR', defaultValue: false);
  static const bool isStorage = bool.fromEnvironment('IS_STORAGE', defaultValue: true);

  // UI/Branding
  static const String logoUrl = String.fromEnvironment('LOGO_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/twinklub_png_logo.png');
  static const String splashUrl = String.fromEnvironment('SPLASH_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/twinklub_png_logo.png');
  static const String splashBgUrl = String.fromEnvironment('SPLASH_BG_URL', defaultValue: '');
  static const String splashBgColor = String.fromEnvironment('SPLASH_BG_COLOR', defaultValue: '#cbdbf5');
  static const String splashTagline = String.fromEnvironment('SPLASH_TAGLINE', defaultValue: 'TWINKLUB');
  static const String splashTaglineColor = String.fromEnvironment('SPLASH_TAGLINE_COLOR', defaultValue: '#a30237');
  static const String splashAnimation = String.fromEnvironment('SPLASH_ANIMATION', defaultValue: 'zoom');
  static const String splashDuration = String.fromEnvironment('SPLASH_DURATION', defaultValue: '4');

  // Bottom Menu Configuration
  static const String bottommenuItems = String.fromEnvironment('BOTTOMMENU_ITEMS', defaultValue: '[{"label":"Home","icon":{"type":"preset","name":"home_outlined"},"url":"https://twinklub.com/"},{"label":"New Arraivals","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/card.svg","icon_size":"24"},"url":"https://www.twinklub.com/collections/new-arrivals"},{"label":"Collections","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/about.svg","icon_size":"24"},"url":"https://www.twinklub.com/collections/all"},{"label":"Contact","icon":{"type":"custom","icon_url":"https://raw.githubusercontent.com/prasanna91/QuikApp/main/contact.svg","icon_size":"24"},"url":"https://www.twinklub.com/account"}]');
  static const String bottommenuBgColor = String.fromEnvironment('BOTTOMMENU_BG_COLOR', defaultValue: '#FFFFFF');
  static const String bottommenuIconColor = String.fromEnvironment('BOTTOMMENU_ICON_COLOR', defaultValue: '#6d6e8c');
  static const String bottommenuTextColor = String.fromEnvironment('BOTTOMMENU_TEXT_COLOR', defaultValue: '#6d6e8c');
  static const String bottommenuFont = String.fromEnvironment('BOTTOMMENU_FONT', defaultValue: 'DM Sans');
  static const String bottommenuFontSize = String.fromEnvironment('BOTTOMMENU_FONT_SIZE', defaultValue: '12');
  static const bool bottommenuFontBold = bool.fromEnvironment('BOTTOMMENU_FONT_BOLD', defaultValue: false);
  static const bool bottommenuFontItalic = bool.fromEnvironment('BOTTOMMENU_FONT_ITALIC', defaultValue: false);
  static const String bottommenuActiveTabColor = String.fromEnvironment('BOTTOMMENU_ACTIVE_TAB_COLOR', defaultValue: '#a30237');
  static const String bottommenuIconPosition = String.fromEnvironment('BOTTOMMENU_ICON_POSITION', defaultValue: 'above');

  // Firebase Configuration
  static const String firebaseConfigAndroid = String.fromEnvironment('FIREBASE_CONFIG_ANDROID', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/google-services-TK.json');
  static const String firebaseConfigIos = String.fromEnvironment('FIREBASE_CONFIG_IOS', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/GoogleService-Info-TK.plist');

  // iOS Signing Configuration
  static const String appleTeamId = String.fromEnvironment('APPLE_TEAM_ID', defaultValue: '9H2AD7NQ49');
  static const String apnsKeyId = String.fromEnvironment('APNS_KEY_ID', defaultValue: 'V566SWNF69');
  static const String apnsAuthKeyUrl = String.fromEnvironment('APNS_AUTH_KEY_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_V566SWNF69.p8');
  static const String profileType = String.fromEnvironment('PROFILE_TYPE', defaultValue: 'app-store');
  static const String profileUrl = String.fromEnvironment('PROFILE_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/Twinklub_AppStore.mobileprovision');
  static const String certPassword = String.fromEnvironment('CERT_PASSWORD', defaultValue: 'qwerty123');
  static const String certP12Url = String.fromEnvironment('CERT_P12_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/Certificates.p12');
  static const String certCerUrl = String.fromEnvironment('CERT_CER_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/ios_distribution.cer');
  static const String certKeyUrl = String.fromEnvironment('CERT_KEY_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/private.key');
  static const bool isTestflight = bool.fromEnvironment('IS_TESTFLIGHT', defaultValue: false);
  static const String appStoreConnectKeyIdentifier = String.fromEnvironment('APP_STORE_CONNECT_KEY_IDENTIFIER', defaultValue: 'S95LCWAH99');
  static const String appStoreConnectApiKey = String.fromEnvironment('APP_STORE_CONNECT_API_KEY', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_S95LCWAH99.p8');
  static const String appStoreConnectApiKeyPath = String.fromEnvironment('APP_STORE_CONNECT_API_KEY_PATH', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/AuthKey_S95LCWAH99.p8');
  static const String appStoreConnectIssuerId = String.fromEnvironment('APP_STORE_CONNECT_ISSUER_ID', defaultValue: 'a99a2ebd-ed3e-4117-9f97-f195823774a7');

  // Android Keystore Configuration
  static const String keyStoreUrl = String.fromEnvironment('KEY_STORE_URL', defaultValue: 'https://raw.githubusercontent.com/prasanna91/QuikApp/main/keystore.jks');
  static const String cmKeystorePassword = String.fromEnvironment('CM_KEYSTORE_PASSWORD', defaultValue: 'opeN@1234');
  static const String cmKeyAlias = String.fromEnvironment('CM_KEY_ALIAS', defaultValue: 'my_key_alias');
  static const String cmKeyPassword = String.fromEnvironment('CM_KEY_PASSWORD', defaultValue: 'opeN@1234');

  // Email Notification System
  static const bool enableEmailNotifications = bool.fromEnvironment('ENABLE_EMAIL_NOTIFICATIONS', defaultValue: true);
  static const String emailSmtpServer = String.fromEnvironment('EMAIL_SMTP_SERVER', defaultValue: 'smtp.gmail.com');
  static const String emailSmtpPort = String.fromEnvironment('EMAIL_SMTP_PORT', defaultValue: '587');
  static const String emailSmtpUser = String.fromEnvironment('EMAIL_SMTP_USER', defaultValue: 'prasannasrie@gmail.com');
  static const String emailSmtpPass = String.fromEnvironment('EMAIL_SMTP_PASS', defaultValue: 'lrnu krfm aarp urux');

  // iOS Distribution Options
  static const bool enableDeviceSpecificBuilds = bool.fromEnvironment('ENABLE_DEVICE_SPECIFIC_BUILDS', defaultValue: false);
  static const String installUrl = String.fromEnvironment('INSTALL_URL', defaultValue: '');
  static const String displayImageUrl = String.fromEnvironment('DISPLAY_IMAGE_URL', defaultValue: '');
  static const String fullSizeImageUrl = String.fromEnvironment('FULL_SIZE_IMAGE_URL', defaultValue: '');
  static const String thinning = String.fromEnvironment('THINNING', defaultValue: 'none');

  // iOS Development Options
  static const bool enableDebugBuild = bool.fromEnvironment('ENABLE_DEBUG_BUILD', defaultValue: false);
  static const bool enableDeviceLogging = bool.fromEnvironment('ENABLE_DEVICE_LOGGING', defaultValue: false);
  static const bool enableDebugSymbols = bool.fromEnvironment('ENABLE_DEBUG_SYMBOLS', defaultValue: false);

  // Build Environment Variables
  static const String cmBuildId = String.fromEnvironment('CM_BUILD_ID', defaultValue: '');
  static const String cmBuildDir = String.fromEnvironment('CM_BUILD_DIR', defaultValue: '');
  static const String outputDir = String.fromEnvironment('OUTPUT_DIR', defaultValue: 'output/ios');

  // Helper methods
  static bool get isFirebaseEnabled => pushNotify;
  static bool get isAndroidWorkflow => workflowId.startsWith('android');
  static bool get isIosWorkflow => workflowId.startsWith('ios') || workflowId == 'combined';
  static bool get isCombinedWorkflow => workflowId == 'combined';
  static bool get isAppStoreProfile => profileType == 'app-store';
  static bool get isAdHocProfile => profileType == 'ad-hoc';
  static bool get isEnterpriseProfile => profileType == 'enterprise';
  static bool get isDevelopmentProfile => profileType == 'development';
}
EOF

echo "✅ Environment configuration generated successfully!"
echo "📁 File: lib/config/env_config.dart"
echo "🔧 Variables: All environment variables are now available in Dart code" 